import { theme } from '../theme'
import { CSSProperties } from 'react'

export const inventoryStyles: Record<string, CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 700,
    color: theme.colors.textPrimary,
    letterSpacing: '-0.01em',
  },
  totalBadge: {
    fontSize: '12px',
    fontWeight: 600,
    padding: '4px 12px',
    borderRadius: '99px',
    background: 'rgba(61, 75, 158, 0.08)',
    color: '#3D4B9E',
    border: '1px solid rgba(61, 75, 158, 0.15)',
  },
  tabsRow: {
    display: 'flex',
    gap: '6px',
    background: 'rgba(0,0,0,0.03)',
    padding: '4px',
    borderRadius: '12px',
    alignSelf: 'flex-start',
  },
  tabActive: {
    padding: '6px 18px',
    borderRadius: '9px',
    background: '#fff',
    color: '#3D4B9E',
    fontSize: '13px',
    fontWeight: 700,
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    border: 'none',
    cursor: 'pointer',
  },
  inventoryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '12px',
    maxHeight: '320px',
    overflowY: 'auto',
    padding: '4px',
  },
  inventoryItem: {
    background: '#fff',
    borderRadius: '16px',
    padding: '16px 10px 12px',
    border: '2px solid transparent',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
  },
  inventoryItemActive: {
    borderColor: '#3D4B9E',
    background: 'rgba(184, 192, 255, 0.15)',
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 12px rgba(61, 75, 158, 0.12)',
  },
  qtyBadge: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    fontSize: '10px',
    fontWeight: 800,
    background: '#3D4B9E',
    color: '#fff',
    borderRadius: '6px',
    padding: '2px 6px',
    zIndex: 2,
  },
  inventoryItemName: {
    fontSize: '12px',
    color: theme.colors.textPrimary,
    textAlign: 'center',
    fontWeight: 600,
    margin: 0,
    lineHeight: 1.2,
  },
  bonusPill: {
    fontSize: '10px',
    fontWeight: 700,
    background: '#E0E7FF',
    color: '#4338CA',
    borderRadius: '99px',
    padding: '2px 8px',
    marginTop: '2px',
  },
  usePanel: {
    background: '#fff',
    borderRadius: '20px',
    padding: '16px',
    border: '1px solid rgba(0,0,0,0.06)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.06)',
    marginTop: 'auto',
  },
  btnPrimary: {
    padding: '10px 24px',
    borderRadius: '12px',
    border: 'none',
    background: '#3D4B9E',
    color: '#fff',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: '0 4px 12px rgba(61, 75, 158, 0.25)',
  },
  emptyBox: {
    background: '#fff',
    borderRadius: '24px',
    padding: '3rem 2rem',
    border: '2px dashed rgba(0,0,0,0.08)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
  },
  msgBanner: {
    padding: '12px',
    borderRadius: '12px',
    fontSize: '13px',
    fontWeight: 600,
    textAlign: 'center',
    animation: 'fadeIn 0.3s ease',
  }
}